--Lab 21

--Implement Intermediate Common Table Expressions (CTE) for Query Simplification 

--From the table STUDENT perform the following queries:  

--Part – A: 

--1. Display all students whose SPI is greater than 8. 
WITH DHAIRYAAAAA AS(
	SELECT * FROM STUDENT
	WHERE SPI > 8
)
SELECT * FROM DHAIRYAAAAA

--2. Display average SPI of all students.
WITH DHAIRYAYAYA AS (
	SELECT AVG(SPI) AS AVG_SPI FROM STUDENT
)
SELECT * FROM DHAIRYAYAYA

--3. Display total number of students in each branch.
WITH DHAIRYAYAYA AS (
	SELECT BRANCH, COUNT(SPI) AS TOTAL_STUDENTS
	FROM STUDENT
	GROUP BY BRANCH
)
SELECT * FROM DHAIRYAYAYA

--4. Display students who belong to RAJKOT city. 
WITH DHAIRYAYAYA AS(
	SELECT * FROM STUDENT
	WHERE CITY = 'RAJKOT'
)
SELECT * FROM DHAIRYAYAYA

--5. Find branch names that appear more than once.
WITH DHAIRYAYAYA AS (
	SELECT BRANCH, COUNT(BRANCH) AS BRANCH_COUNT
	FROM STUDENT
	GROUP BY BRANCH
)
SELECT * FROM DHAIRYAYAYA
WHERE BRANCH_COUNT > 1

--6. Display row number for each student. 
WITH DHAIRYAYAYA AS (
	SELECT *, ROW_NUMBER() OVER (ORDER BY STDID) AS [SR.NO.]
	FROM STUDENT
)
SELECT * FROM DHAIRYAYAYA

--7. Display top 3 students based on SPI. 
WITH DHAIRYAYAYA AS (
	SELECT *, DENSE_RANK() OVER (ORDER BY SPI) AS RK
	FROM STUDENT
)
SELECT * FROM DHAIRYAYAYA
WHERE RK <= 3

--8. Display students having maximum SPI. 
WITH DHAIRYAYAYA AS (
	SELECT * FROM STUDENT
	WHERE SPI = (
		SELECT MAX(SPI) FROM STUDENT
	)
)
SELECT * FROM DHAIRYAYAYA

--9. Display students having minimum SPI. 
WITH DHAIRYAYAYA AS (
	SELECT * FROM STUDENT
	WHERE SPI = (
		SELECT MIN(SPI) FROM STUDENT
	)
)
SELECT * FROM DHAIRYAYAYA

--10. Display branch -wise rank of students. 
 WITH DHAIRYAYAYA AS (
	SELECT *, RANK() OVER (PARTITION BY BRANCH ORDER BY SPI) AS RK
	FROM STUDENT
)
SELECT * FROM DHAIRYAYAYA


--Part – B: 

--11. Display students SPI average belonging to Computer branch. 
WITH DHAIRYAYAYA AS (
	SELECT AVG(SPI) AS AVG_SPI FROM STUDENT
	WHERE BRANCH = 'COMPUTER'
)
SELECT * FROM DHAIRYAYAYA

--12. Display students whose SPI is greater than average SPI of his/her branch.
WITH DHAIRYAYAYA AS (
	SELECT * FROM STUDENT AS S1
	WHERE SPI > (
		SELECT AVG(SPI) FROM STUDENT
		WHERE BRANCH = S1.BRANCH
	)
)
SELECT * FROM DHAIRYAYAYA

--13. Display branch having more than 2 students.
WITH DHAIRYAYAYA AS (
	SELECT BRANCH, COUNT(STDID) AS STUDENT_COUNT
	FROM STUDENT
	GROUP BY BRANCH
)
SELECT * FROM DHAIRYAYAYA
WHERE STUDENT_COUNT > 1

--14. Display branches having average SPI between 7 and 9
WITH DHAIRYAYAYA AS (
	
	SELECT BRANCH, AVG(SPI) AS BRANCHWISE_AVG_SPI FROM STUDENT
	GROUP BY BRANCH
	HAVING AVG(SPI) BETWEEN 7 AND 9
)
SELECT * FROM DHAIRYAYAYA

--15. Display students whose SPI is lower than overall average SPI. 
WITH DHAIRYAYAYA AS (
	SELECT *
	FROM STUDENT
	WHERE SPI < (
		SELECT AVG(SPI) FROM STUDENT
	)
)
SELECT * FROM DHAIRYAYAYA


--Part – C: 

--16. Display branches having exactly one student.
WITH DHAIRYAYAYA AS (
	SELECT BRANCH, COUNT(STDID) AS STUDENT_COUNT
	FROM STUDENT
	GROUP BY BRANCH
)
SELECT * FROM DHAIRYAYAYA
WHERE STUDENT_COUNT = 1

--17. Display branch having highest average SPI. 
WITH DHAIRYAYAYA AS (
	SELECT BRANCH, AVG(SPI) AS BRANCHWISE_AVG_SPI  FROM STUDENT
	GROUP BY BRANCH
),
DHAIRYAYAYA_MAX AS (
	SELECT BRANCH,
	ROW_NUMBER() OVER (ORDER BY BRANCHWISE_AVG_SPI DESC) AS MAX_BRANCHWISE_AVG_SPI
	FROM DHAIRYAYAYA
)
SELECT BRANCH FROM DHAIRYAYAYA_MAX
WHERE MAX_BRANCHWISE_AVG_SPI = 1

--18. Display branch having lowest average SPI. 
WITH DHAIRYAYAYA AS (
	SELECT BRANCH, AVG(SPI) AS BRANCHWISE_AVG_SPI  FROM STUDENT
	GROUP BY BRANCH
),
DHAIRYAYAYA_MAX AS (
	SELECT BRANCH,
	ROW_NUMBER() OVER (ORDER BY BRANCHWISE_AVG_SPI) AS MAX_BRANCHWISE_AVG_SPI
	FROM DHAIRYAYAYA
	WHERE BRANCH IS NOT NULL
)
SELECT BRANCH FROM DHAIRYAYAYA_MAX
WHERE MAX_BRANCHWISE_AVG_SPI = 1

--19. Display students whose SPI is lower than branch average SPI. 
WITH DHAIRYAYAYA AS (
	SELECT * FROM STUDENT AS S1
	WHERE SPI < (
		SELECT AVG(SPI) FROM STUDENT
		WHERE BRANCH = S1.BRANCH
	)
)
SELECT * FROM DHAIRYAYAYA

--20. Display branches having maximum number of students.
WITH DHAIRYAYAYA AS (
	SELECT BRANCH, COUNT(STDID) AS STUDENT_COUNT
	FROM STUDENT
	GROUP BY BRANCH
),
DHAIRYAYAYA_MAX_STUDENT AS (
	SELECT BRANCH, STUDENT_COUNT
	FROM DHAIRYAYAYA
	WHERE STUDENT_COUNT = (
		SELECT MAX(STUDENT_COUNT) FROM DHAIRYAYAYA
	)
)
SELECT * FROM DHAIRYAYAYA_MAX_STUDENT