--Implement Advance Common Table Expressions (CTE) for Query Simplification 

CREATE TABLE CUSTOMER_ALL
(
ORDERID INT,
CNAME VARCHAR(15),
PRODUCT VARCHAR(15),
CATEGORY VARCHAR(15),
AMOUNT INT,
ORDERYEAR INT,
CITY VARCHAR(15)
)

INSERT INTO CUSTOMER_ALL
VALUES
(101, 'RAHUL', 'LAPTOP', 'ELECTRONICS', 65000, 2024, 'RAJKOT'), 
(102, 'PRIYA', 'MOBILE', 'ELECTRONICS', 25000, 2023, 'SURAT'),
(103, 'AMIT', 'TABLE', 'FURNITURE' ,12000, 2022, 'AHMEDABAD'),
(104, 'NEHA', 'CHAIR', 'FURNITURE', 8000, 2024, 'BARODA'),
(105, 'VISHAL', 'TV', 'ELECTRONICS', 45000, 2025, 'MORBI'),
(106, 'RIYA', 'SOFA', 'FURNITURE', 30000, 2023, 'SURAT'),
(107, 'MEHUL', 'AC', 'ELECTRONICS', 40000, 2022, 'RAJKOT'),
(108, 'KRUNAL', 'BED', 'FURNITURE', 40000, 2025, 'JAMNAGAR')


--From the table CUSTOMER perform the following queries:  

--Part – A: 

--1. Display top 3 highest amount orders. 
WITH TOP3_AMT AS (
	SELECT *,
	ROW_NUMBER() OVER (ORDER BY AMOUNT DESC) AS [SR.NO.]
	FROM CUSTOMER_ALL
)
SELECT TOP 3 * FROM TOP3_AMT

--2. Display second highest order amount. 
WITH SECOND_HIGHEST AS (
	SELECT ROW_NUMBER() OVER (ORDER BY AMOUNT DESC) AS [SR.NO.],*
	FROM CUSTOMER_ALL
)
SELECT * FROM SECOND_HIGHEST
WHERE [SR.NO.] = 2

--3. Display customers whose order amount is greater than category average amount. 
WITH CATEGORY_WISE_AVG_AMT AS (
	SELECT *, AVG(AMOUNT) OVER (PARTITION BY CATEGORY) AS AVG_AMT 
	FROM CUSTOMER_ALL
)
SELECT * FROM CATEGORY_WISE_AVG_AMT
WHERE AVG_AMT < AMOUNT 

--4. Display categories having average amount greater than 30000. 
WITH CATEGORY_WISE_AVG_AMT AS (
	SELECT CATEGORY, AVG(AMOUNT) AS AVG_AMT 
	FROM CUSTOMER_ALL
	GROUP BY CATEGORY
)
SELECT CATEGORY, AVG_AMT
FROM CATEGORY_WISE_AVG_AMT
WHERE AVG_AMT > 30000

--5. Display highest amount order from each category. 
WITH CATEGORY_WISE_HIGHEST_AMT AS (
	SELECT *,
	ROW_NUMBER() OVER (PARTITION BY CATEGORY ORDER BY AMOUNT DESC) AS RWN_AMT 
	FROM CUSTOMER_ALL
)
SELECT CATEGORY, AMOUNT
FROM CATEGORY_WISE_HIGHEST_AMT
WHERE RWN_AMT = 1

--6. Display lowest amount order from each category. 
WITH CATEGORY_WISE_LOWEST_AMT AS (
	SELECT *,
	ROW_NUMBER() OVER (PARTITION BY CATEGORY ORDER BY AMOUNT) AS RWN_AMT 
	FROM CUSTOMER_ALL
)
SELECT CATEGORY, AMOUNT
FROM CATEGORY_WISE_LOWEST_AMT
WHERE RWN_AMT = 1

--7. Display categories having more than 3 orders. 
WITH CATEGORY_WISE_TOP3_ORDER AS (
	SELECT *,
	ROW_NUMBER() OVER (PARTITION BY CATEGORY ORDER BY AMOUNT) AS RWN_AMT 
	FROM CUSTOMER_ALL
)
SELECT CATEGORY
FROM CATEGORY_WISE_TOP3_ORDER
WHERE RWN_AMT > 3

--8. Display city-wise total order amount. 
WITH CITY_WISE_TOTAL_AMT AS (
	SELECT CITY, SUM(AMOUNT) AS TOTAL_AMT 
	FROM CUSTOMER_ALL
	GROUP BY CITY
)
SELECT CITY, TOTAL_AMT
FROM CITY_WISE_TOTAL_AMT

--9. Display category having highest average order amount. 
--WITH CAT_HIGH_AVG_AMT AS (
--	SELECT CATEGORY, AVG(AMOUNT) AS CAT_AVG_AMT
--	FROM CUSTOMER_ALL
--	GROUP BY CATEGORY
--)
--SELECT CATEGORY, MAX(CAT_AVG_AMT) AS MAX_AVG_AMT
--FROM CAT_HIGH_AVG_AMT
--GROUP BY CATEGORY

--10. Display cumulative order amount in ascending order of amount. 
WITH CUM_AMT_TABLE AS (
	SELECT *, SUM(AMOUNT) OVER (ORDER BY AMOUNT) AS CUM_AMT
	FROM CUSTOMER_ALL
)
SELECT * FROM CUM_AMT_TABLE

 
--Part – B: 

--11. Display category-wise top 2 highest amount orders. 
WITH CATEGORY_WISE_TOP2_ORDER AS (
	SELECT *,
	ROW_NUMBER() OVER (PARTITION BY CATEGORY ORDER BY AMOUNT DESC) AS RWN_AMT 
	FROM CUSTOMER_ALL
)
SELECT *
FROM CATEGORY_WISE_TOP2_ORDER
WHERE RWN_AMT < 3

--12. Display customers whose amount is closest to category average amount. 
--WITH AVG_AMT AS (
--	SELECT CATEGORY, AVG(AMOUNT) AS CAT_AVG_AMT
--	FROM CUSTOMER_ALL
--	GROUP BY CATEGORY
--),
--CLOSE_AVG_AMT AS (
--	SELECT CATEGORY, ABS(AMOUNT - CAT_AVG_AMT) AS DIFF_AMT
--	FROM 
--)

--13. Display previous, current and next order amount together. 
WITH PRE_CUR_NEXT_AMT AS (
	SELECT *,
	LAG(AMOUNT) OVER (ORDER BY AMOUNT) AS PRE_AMT,
	AMOUNT AS CUR_AMT,
	LEAD(AMOUNT) OVER (ORDER BY AMOUNT) AS NEXT_AMT
	FROM CUSTOMER_ALL
)
SELECT * FROM PRE_CUR_NEXT_AMT

--14. Display customers whose amount is greater than previous customer's amount. 
WITH PRE_GRE_CUR_AMT AS (
	SELECT *,
	LAG(AMOUNT) OVER (ORDER BY AMOUNT DESC) AS PRE_AMT
	FROM CUSTOMER_ALL
)
SELECT * FROM PRE_GRE_CUR_AMT
WHERE PRE_AMT > AMOUNT

--15. Display customers whose rank and dense rank are different. 
WITH DIFF_RK_DRK AS (
	SELECT *,
	RANK() OVER (ORDER BY AMOUNT DESC) AS RK,
	DENSE_RANK() OVER (ORDER BY AMOUNT DESC) AS DRK
	FROM CUSTOMER_ALL
)
SELECT * FROM DIFF_RK_DRK
WHERE RK != DRK

 
--Part – C: 

--16. Display orders whose amount is neither highest nor lowest in their category. 
WITH AMT_HIGH_LOW AS (
	SELECT *,
	MAX(AMOUNT) OVER (PARTITION BY CATEGORY) AS MAX_AMT,
	MIN(AMOUNT) OVER (PARTITION BY CATEGORY) AS MIN_AMT
	FROM CUSTOMER_ALL
),
AMT_NHIGH_NLOW AS (
	SELECT ORDERID, CNAME, PRODUCT, CATEGORY, AMOUNT, ORDERYEAR, CITY
	FROM AMT_HIGH_LOW
	WHERE AMOUNT > MIN_AMT AND AMOUNT < MAX_AMT
)
SELECT * FROM AMT_NHIGH_NLOW

--17. Display category-wise difference between highest and lowest amount. 
WITH CAT_WISE_DIFF_HIGH_LOW AS (
	SELECT CATEGORY, (MAX(AMOUNT) - MIN(AMOUNT)) AS DIFF_MAX_MIN_AMT
	FROM CUSTOMER_ALL
	GROUP BY CATEGORY
)
SELECT * FROM CAT_WISE_DIFF_HIGH_LOW

--18. Display customers whose amount is greater than all FURNITURE category orders. 
WITH FUR_MAX_AMT AS (
 SELECT MAX(AMOUNT) AS MAX_AMT
 FROM CUSTOMER_ALL
 WHERE CATEGORY = 'FURNITURE'
),
AMT_GREATER_FUR_MAX_AMT AS (
	SELECT * FROM CUSTOMER_ALL
	CROSS JOIN FUR_MAX_AMT
	WHERE AMOUNT > MAX_AMT
)
SELECT * FROM AMT_GREATER_FUR_MAX_AMT

--19. Display categories where all orders are above 10000. 
WITH CAT_HAVE_AMT_ABOVE_10000 AS (
	SELECT CATEGORY
	FROM CUSTOMER_ALL
	GROUP BY CATEGORY
	HAVING MIN(AMOUNT) > 10000
)
SELECT * FROM CAT_HAVE_AMT_ABOVE_10000

--20. Display customers whose amount difference from category topper is minimum. 
WITH CAT_TOP AS (
	SELECT CNAME, CATEGORY, MAX(AMOUNT) OVER (PARTITION BY CATEGORY) -AMOUNT AS DIFF_AMT
	FROM CUSTOMER_ALL
),
CAT_TOP_ROW_NUM AS (
	SELECT *, DENSE_RANK() OVER (PARTITION BY CATEGORY ORDER BY DIFF_AMT) AS RN
	FROM CAT_TOP
),
AMT_DIFF_MIN_FROM_CAT_TOP AS (
	SELECT CNAME, CATEGORY, DIFF_AMT
	FROM CAT_TOP_ROW_NUM
	WHERE RN = 2
)
SELECT * FROM AMT_DIFF_MIN_FROM_CAT_TOP